.\" Copyright (c) 2019 Tim Kuijsten
.\"
.\" Permission to use, copy, modify, and/or distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate: November 14 2019 $
.Dt WIRESEP.CONF 5
.Os
.Sh NAME
.Nm wiresep.conf
.Nd WireSep configuration file
.Sh DESCRIPTION
.Nm
is the configuration file used by
.Xr wiresep 8 .
The file consists of global settings, interface specific settings and peer
specific settings.
All global settings can be overridden per interface and some global and
interface specific settings can be overridden per peer.
.Ss GLOBAL SETTINGS
The following global settings are recognized:
.Bl -tag -width Ds
.It Ic group Ar name
Set the group as which to run
.Xr wiresep 8 .
.Ar name
must be either the name of an existing group from the
.Xr group 5
database or an id in the range of 1 to 65535.
If not set it defaults to the primary group of the effective
.Ar user .
.It Ic interface Ar name Brq ...
The name of an interface.
.Ar name
must start with
.Dq tun
followed by a number.
The named interface must exist in
.Pa /dev
and can be created with
.Xr MAKEDEV 8 .
See the section about interface specific settings for what can be contained in
the block.
.It Ic log facility Ar facility
Set the log facility as used by
.Xr syslog 3 .
.Ar facility
must be one of auth, authpriv, cron, daemon, ftp, kern, lpr, mail, news, user,
uucp or local0 through local7.
.It Ic pskfile Ar file
The name of a file that contains a pre-shared key for global use with all peers
on all interfaces.
The use of a pre-shared key is optional.
If the file
.Pa /etc/wiresep/global.psk
exists it is automatically used.
This setting can be overridden per interface and per peer.
See
.Sx KEY FILE FORMAT
for the format of a pre-shared key file.
.It Ic user Ar name
Set the user as which to run
.Xr wiresep 8 .
.Ar name
must be either the name of an existing user in the
.Xr passwd 5
database or an id in the range of 1 to 65535.
If a name is specified the primary group of this user will be used as the group
of the process.
If an id is specified for
.Ar name
then the group of the process will be set to the same id.
If not set it defaults to the user
.Dq _wiresep .
.El
.Ss INTERFACE SPECIFIC SETTINGS
The following interface specific settings are recognized:
.Bl -tag -width Ds
.It Ic desc Ar text
A descriptive
.Ar text
for the interface as showed by
.Xr ifconfig 8 .
If not set it defaults to the public key of the interface.
.It Ic ifaddr Ar ip/mask Op ...
The ip address and mask of the interface in CIDR notation.
Multiple addresses may be configured.
This setting is required since configuration via
.Xr hostname.if 5
is not yet supported.
.It Ic listen Ar ip:port Op ...
The ip address and port on which to listen for encrypted incoming packets.
Multiple address and port combinations may be configured.
This setting is optional and determines whether to operate in server or
client-only mode.
.It Ic privkeyfile Ar file
The name of a file that contains the private key for this interface.
This setting is mandatory, but if it is not set explicitly it will implicitly
default to
.Pa /etc/wiresep/tunX.key
where
.Sq X
is the number of the interface.
See
.Sx KEY FILE FORMAT
for the format of a private key file.
.It Ic peer Oo Ar name Oc Brq ...
A peer with an optional
.Ar name
followed by a required block containing peer specific settings.
.Ar name
is used in the logs.
If it is not set the first eight characters of the peers public key are used.
See the section about peer specific settings for what can be contained in the
block.
.It Ic pskfile Ar file
The name of a file that contains a pre-shared key for communication with all
peers on this interface.
The use of a pre-shared key is optional.
If the file
.Pa /etc/wiresep/tunX.psk
exists it is automatically used, where
.Sq X
is the number of the interface.
An interface specific pre-shared key overrides any global
.Ar pskfile .
See
.Sx KEY FILE FORMAT
for the format of a pre-shared key file.
.El
.Pp
Note that all global settings can be used within an interface block to override
the global setting.
.Ss PEER SPECIFIC SETTINGS
The following peer specific settings are recognized:
.Bl -tag -width Ds
.It Ic allowedips Ar ip/mask Op ...
The ip addresses that this peer is allowed to use as a source address.
.Ar 0.0.0.0/0
means any IPv4 address.
.Ar ::/0
means any IPv6 address.
.Ar *
is a shorthand for
.Ar ::/0 0.0.0.0/0 .
This setting is required.
.It Ic endpoint Ar ip:port
A known endpoint for this peer.
.It Ic pskfile Ar file
The name of a file that contains a pre-shared key for communication with this
peer.
The use of a pre-shared key is optional.
If the file
.Pa /etc/wiresep/tunX.peername.psk
or
.Pa /etc/wiresep/peername.psk
exists it is automatically used, where
.Sq X
is the number of the interface and
.Ar peername
is the
.Ar name
that can be specified with the interface specific
.Ic peer
setting.
A peer specific pre-shared key overrides any global or interface specific
.Ar pskfile .
See
.Sx KEY FILE FORMAT
for the format of a pre-shared key file.
.It Ic pubkey Ar key
The peers public key.
This setting is required.
.El
.Ss KEY FILE FORMAT
The
.Ic privkeyfile
and
.Ic pskfile
settings refer to a
.Ar file
that contains either a private key or a
pre-shared key, respectively.
Each file should contain only one key.
The key itself must be encoded in Base64.
Any blank line in the file or lines that start with a
.Sq #
are ignored, as well as any text that follows a key.
The file must be owned by the superuser and may not have any permission bits set
for the group or others.
.Sh EXAMPLES
A config file that uses the tun5 device with the internal ip addresses
2001:db8::7 and 172.16.0.1 and allows communication with the peer Jane and Joe.
Jane is allowed to use any source ip, while Joe may only use 2001:db8::4 or
172.16.0.11/30 as the source ip of his packets.
The private key for the tun5 interface is stored in the default location:
.Pa /etc/wiresep/tun5.key .
Furthermore, with Joe a peer specific pre-shared key is used for quantum-proof
encryption by simply storing a Base64 encoded key in a file named
.Pa /etc/wiresep/joe.psk .
.Bd -literal -offset indent
interface tun5 {
	listen 198.51.100.7:1234
	ifaddr 2001:db8::7/126 172.16.0.1/24

	peer jane {
		pubkey BhyBpDfD7joIPPpjBW/g/Wdhiu3iVOzQhKodbsLqJ3A=
		allowedips *
	}

	peer joe {
		pubkey AhyBpDfD7joIPPpjBW/g/Wdhiu3iVOzQhKodbsLqJ3A=
		allowedips 2001:db8::4 172.16.0.11/30
	}
}
.Ed
.Pp
In order to let
.Xr wiresep 8
create the tun5 device, it must exist in the
.Pa /dev
tree.
This can be done as follows:
.Bd -literal -offset indent
	cd /dev
	doas ./MAKEDEV tun5
.Ed
.Pp
Note that
.Pa /etc/hostname.tun5
should not be created as
.Xr wiresep 8
should do the setup and teardown of the interface by itself.
.Sh SEE ALSO
.Xr wiresep-keygen 1 ,
.Xr MAKEDEV 8 ,
.Xr wiresep 8
.Sh AUTHORS
.An -nosplit
.An Tim Kuijsten
.Sh CAVEATS
Currently the use of
.Xr hostname.if 5
or manual creation of the tunnel interface using
.Xr ifconfig 8
is not well-tested and it is recommended to let
.Xr wiresep 8
do the setup and teardown of the interface.
